version: '2'

services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    ports:
      - "80:80"
    links:
      - db
      - cache
    restart: always

  db:
    container_name: db
    image: mariadb:latest
    env_file: db.env
    restart: always

  cache:
    container_name: memcache
    image: sylvainlasnier/memcached
    restart: always
